### ISSUE TITLE
users to orgs

### ISSUE THREAD

**Issue by fayasnoushad** [VasudevJaiswal/Jaidevstudio-API#1]
Change api users ( https://api.github.com/users/jaidevstudio ) to orgs ( https://api.github.com/orgs/jaidevstudio )

**Comment by VasudevJaiswal** [comment]
@FayasNoushad 
1. how to make py api using github  ?  plz tell me
2. thank you

**Comment by fayasnoushad** [comment]
> @FayasNoushad
> 
> 1. how to make py api using github  ?  plz tell me
> 2. thank you

Use [Requests Library](https://github.com/psf/requests) and [GitHub Official API](https://api.fayas.me).

**Comment by VasudevJaiswal** [comment]
Thank you @FayasNoushad

**Comment by VasudevJaiswal** [comment]
@FayasNoushad 
But any other information or Videos please send me link

**Comment by fayasnoushad** [comment]
No videos

**Comment by fayasnoushad** [comment]
Search about requests tutorials

**Comment by VasudevJaiswal** [comment]
I can't find exact information

**Comment by fayasnoushad** [comment]
So many requests tutorials available on YouTube. You can use that method for fetching json information from github api.

**Comment by VasudevJaiswal** [comment]
I talk about python api

**Comment by VasudevJaiswal** [comment]
I talk about python api

**Comment by fayasnoushad** [comment]
I too. Learn about requests.
